cpm/domain/compilation_recipes/build.py
cpm/domain/compilation_recipes/cmake.py
cpm/domain/compilation_recipes/test_recipe.py
cpm/domain/plugin_loader.py
cpm/domain/project.py
cpm/domain/project_loader.py
test/compilation_recipes/test_build_recipe.py
test/compilation_recipes/test_test_recipe.py
test/domain/test_plugin_loader.py
test/domain/test_project_loader.py

Closes #28 
The project.yaml syntax has been extended to support cflags per package.

CFLAGS can now be defined per package

---

cpm/domain/compilation_recipes/build.py
cpm/domain/compilation_recipes/cmake.py
cpm/domain/compilation_recipes/test_recipe.py
cpm/domain/project.py
cpm/domain/project_loader.py
setup.py
test/compilation_recipes/test_build_recipe.py
test/compilation_recipes/test_test_recipe.py
test/domain/test_project_loader.py

Closes #44 
The current option is now available:
```yaml
link_options:
libraries: ['pthread']
```
Which will translate into the following CMake rule for both tests and the final binary:
`target_link_libraries(cpm-hub pthread)`

Add support for specifying libraries to link in project.yaml

---

cpm/__init__.py
cpm/api/publish.py
cpm/domain/compilation_recipes/cmake.py
cpm/domain/plugin_packager.py
cpm/domain/plugin_uploader.py
cpm/domain/publish_service.py
cpm/infrastructure/filesystem.py
cpm/infrastructure/http_client.py
requirements.txt
test/api/test_api_create.py
test/api/test_api_publish.py
test/api/test_api_test.py
test/domain/test_plugin_packager.py
test/domain/test_publish_service.py

This functionality is very preliminary. It currently packs the project descriptor and packages directories into a `zip` file and then uploads it via a `multipart/form-data` request to a predefined URL at `https://www.cpm-hub.com/plugins`. 
Part of #27.

27 implement publish command

---

cpm/__init__.py
cpm/api/project_actions.py
cpm/domain/project.py
cpm/domain/project_loader.py
cpm/infrastructure/project_action_runner.py
test/api/test_api_project_actions.py
test/domain/test_project_loader.py
test/infrastructure/test_project_action_runner.py

Additional actions apart from the built-in ones can be defined in the project descriptor:
```yaml
project_name: project
actions:
deploy: "echo Deploy!"
```
The previous description enables a new `deploy` action in the project:
```bash
$ cpm deploy
Deploy!
CPM: finished "deploy"
```
Closes #45

implemented support for project actions

---

cpm/__init__.py
scripts/cpm_bash_completion

Implemented a basic script that can be sourced for bash completion:
```bash
$ cpm <tab><tab>
build    clean    create   deploy   install  publish  target   test
...
$ cpm c<tab><tab>
clean   create  
```
This doesn't solve the problem of installing the bash completion script when installing cpm on the system.

Implemented basic bash completion

---

cpm/api/install.py
cpm/infrastructure/cpm_user_configuration.py
cpm/infrastructure/filesystem.py
cpm/infrastructure/http_client.py
test/infrastructure/test_cpm_user_configuration.py

This pull requests allows the user to configure the CPM Hub url to use in a file in its home directory. That file must have the name `.cpm.yaml` and must be located in the user home directory (`~/.cpm.yaml`).
The file is a YAML formatted file and currently it supports the following syntax:
```yaml
cpm_hub_url: http://localhost:8000
```
Closes #58

Store global CPM configuration in user home directory

---

cpm/api/build.py
cpm/api/test.py
cpm/domain/cmake_recipe.py
test/api/test_api_build.py
test/domain/test_cmake_recipe.py

This MR processes compilation errors in both build and test commands. A compilation error will stop further commands from being executed.
Closes #89

Process compilation errors for build and test commands

---

cpm/domain/cmake_recipe.py
cpm/domain/test_service.py
test/domain/test_cmake_recipe.py
test/domain/test_test_service.py

This MR refactors the test run function at cmake recipe. It fixes the existing problem when running tests using patterns. Individual failures are not taken into account.
Closes #73

Fix tests reported as passed when running with file pattern

---

cpm/domain/cmake.py
cpm/domain/cmake_recipe.py
cpm/domain/project.py
cpm/domain/project_loader.py
cpm/infrastructure/cpm_user_configuration.py
test/domain/test_cmake_recipe.py
test/domain/test_project_loader.py

This pull request allows the user to define project global flags through a new `compile_flags` option in the project descriptor.
This pull request also re-organizes the project compilation, compiling the plugins with sources separately as libraries and then linking the project against them. This way, some possible conflicts when linking c++ projects against c plugins (or viceversa) are removed.

Allow user to define global compile flags

---

cpm/domain/cmake_recipe.py
test/domain/test_cmake_recipe.py
test/domain/test_project_loader.py

This pull request fixes the problem arised after compiling plugins as libraries. Plugins need to be compiled before project link_libraries to keep dependencies.
Closes #102

102 compile with libraries in right order

---

.github/workflows/pythonapp.yml
setup.cfg

This pull request sets up the github workflow so that the pypi package is automatically published after a github release is generated. 
Closes #108

Publish pypi package on release

---

cpm/api/create.py
cpm/api/init.py
cpm/domain/creation_service.py
cpm/domain/plugin_packager.py
cpm/domain/project.py
cpm/domain/project_loader.py
test/api/test_api_create.py
test/api/test_api_init.py
test/domain/test_creation_service.py
test/domain/test_project_loader.py
test/e2e/API.robot

This pull request implements the `init` command line api. It allows to initialize the current directory as a CPM project. This makes sense for all those software projects born as git repositories.
The command synopsis is:
```bash
$ cpm init ProjectName
```
The above command will initialize the current directory (`.`) as a CPM project, creating the project descriptor. For now this is the only action taken. The automatic detection of packages is left as an improvement but it might not be feasible (at least without modification of the project sources).
Closes #22

Create project from existing sources

---

cpm/api/publish.py
cpm/infrastructure/cpm_hub_connector_v1.py
cpm/infrastructure/http_client.py
test/api/test_api_publish.py
test/infrastructure/test_cpm_hub_connector_v1.py

With this MR, CPM will display information about the various publication failures, like entering invalid URL, credentials or other errors.
Closes #114

Process and print plugin publication failures

---

cpm/api/install.py
cpm/domain/install_service.py
cpm/infrastructure/cpm_hub_connector_v1.py
test/api/test_api_install.py
test/domain/test_install_service.py
test/infrastructure/test_cpm_hub_connector_v1.py

This pull request sets up the infrastructure to download specific plugin versions from CPM Hub. For the time being, it will only download the latest version of the plugin until the CLI interface is properly defined.
Part of #117

Set infrastructure to allow installation of specific plugin version

---

cpm/api/install.py
cpm/api/update.py
cpm/domain/install_service.py
cpm/domain/project.py
cpm/domain/project_loader.py
cpm/infrastructure/cpm_hub_connector_v1.py
test/api/test_api_install.py
test/domain/test_install_service.py
test/domain/test_project_loader.py

With this pull request, CPM will install all declared plugins in the project descriptor when the user passes no argument to the command line:
```
$ cpm install
```
Closes #88

Allow user installing all declared plugins in project descriptor

---

cpm/domain/bit.py
cpm/domain/install_service.py
test/domain/test_install_service.py

With this PR bits that are up to date will not be installed again unless using the latest version:
```
$ cpm install
bit already installed: cest:1.0
bit already installed: mongoose:6.16
bit already installed: json:3.7.3
bit already installed: fakeit:2.0.5
bit already installed: base64:1.0
bit already installed: blake3:1.0
bit already installed: inih:1.0
CPM: Installed bits
```
Closes #131

Do not re-install up to date bits

---

cpm/domain/bit.py
cpm/domain/bit_loader.py
cpm/domain/install_service.py
test/domain/test_bit_loader.py
test/domain/test_install_service.py

With this pull request, when bits are installed in the project, the dependencies will be followed greedily, so that any transitive dependencies will be installed as well.
Part of #33

Install bit transitive dependencies

---

cpm/domain/install_service.py
cpm/domain/project.py
cpm/domain/project_loader.py
test/domain/test_install_service.py
test/domain/test_project_loader.py

This pull request introduces the concept of `test bit`, that is, bits that are only used in the tests. This avoids installing transitively test bits.
Closes #33

Do not install test bits transitively

---

cpm/domain/cmake_recipe.py
test/domain/test_cmake_recipe.py

Resolve "Bits are not linked in tests when link_options.libraries is empty in project descriptor"

---

cpm/domain/cmake_builder.py
cpm/domain/cmake_recipe.py
cpm/domain/project.py
cpm/domain/project_loader.py
test/domain/test_cmake_recipe.py
test/domain/test_project_loader.py

With this pull request the user will be able to defined test-only packages, that is, packages that are included only for testing. For example, if you want to include a package with mocks, CPM will include the files and the include directories only for the test targets:
```yaml
test_packages:
tests/mocks:
```
Closes #79

Allow defining test only packages

---

cpm/domain/bit_packager.py
cpm/domain/cmake_recipe.py
cpm/domain/creation_service.py
cpm/domain/install_service.py
cpm/domain/project.py
cpm/domain/project_loader.py
test/domain/test_bit_packager.py
test/domain/test_cmake_recipe.py
test/domain/test_creation_service.py
test/domain/test_install_service.py
test/domain/test_project_loader.py

With this PR, the users have available a new `test` field in the project descriptor where the test compilation can be configured. For example, user-defined mocks should be compiled only for test targets. This PR supersedes the previous change at #156.
```yaml
project: 'Project'
test: # the declarations will be used for testing only
bits: []
packages: []
compile_flags: []
link_options: 
libraries: []
```

Allow users to define the compilation configuration for testing only

---

cpm/domain/cmake_recipe.py
setup.cfg
test/domain/test_cmake_recipe.py

This PR makes effective the project descriptor option for defining libraries to be linked only in the tests.

Include libraries for testing only in cmake recipe

---

cpm/__init__.py

With this pull request, `cpm` will print the time taken to execute each action at the end except on failures.
Closes #17

Print action execution time

---

cpm/api/test.py
cpm/domain/project_commands.py

This pull request improves the build process when building the project inside a container. The build is performed inside the container for both the tests and the project binary itself. Tests will not be run inside the container, but in the host (future feature?). 
The container will be automatically removed once the build process finishes. Return codes are forwarded to the host.

Improve compilation and error processing when building inside containers

---

cpm/domain/project/project.py
cpm/domain/project/project_composer.py
cpm/domain/project/project_descriptor.py
cpm/domain/project/project_descriptor_parser.py
cpm/domain/project_commands.py
test/domain/test_project_composer.py
test/domain/test_project_descriptor_parser.py
test/e2e/test_cpm.py

This PR allows the user defining a target `post_build` action. The post-build will be run inside the container and currently it won't be used at all if the project is not compiled inside an image:
```yaml
targets:
default:
image: 'ubuntu:20.04'
post_build: './scripts/create_installer.sh'
```
Closes #194

Allow defining a list of post_build actions to be run inside container

---

cpm/domain/project/project.py
cpm/domain/project/project_composer.py
cpm/domain/project/project_descriptor.py
cpm/domain/project/project_descriptor_parser.py
cpm/domain/project_commands.py
cpm/domain/test_service.py
setup.cfg
test/domain/test_project_composer.py
test/domain/test_project_descriptor_parser.py
test/domain/test_test_service.py
test/e2e/test_cpm.py

This MR adds a new configuration parameter in the project target section that allows the user to specify which container to use to run the tests:
```yaml
targets:
default:
test_image: 'cpmbits/ubuntu:20.04'
```
When tests are run, they will be compiled and executed using the specified image. This again leverages Docker to handle project dependencies when testing, which are likely to be similar to the build dependencies.

Allow tests to be run inside container

---

cpm/domain/cmake/cmakelists_builder.py
cpm/domain/project/project.py
cpm/domain/project/project_composer.py
cpm/domain/project/project_descriptor.py
cpm/domain/project/project_descriptor_parser.py
test/domain/test_cmakelists_builder.py
test/domain/test_project_composer.py
test/domain/test_project_descriptor_parser.py
test/e2e/environment/Dockerfile
test/e2e/test_cpm.py

This pull request adds a new configuration parameter to the project descriptor, allowing the user to specify the toolchain prefix. This allows the user full control over the compiler to be used for the compilation of a specific target. The toolchain prefix is prepended to the compiler name, in this case `gcc`. 
Usage:
```yaml
targets:
default:
toolchain_prefix: 'arm-linux-gnueabihf-'
```

Allow defining the toolchain prefix for each target

---

cpm/api/test.py
cpm/domain/project_commands.py
cpm/domain/test_service.py
requirements.txt
setup.cfg
test/api/test_api_test.py
test/domain/test_test_service.py

With this PR, users will be able to send command line arguments to the testing framework:
```bash
cpm test -- -g -f
```
With the above command, the `-g` and `-f` arguments will be forwarded to the test main.
Closes #237

Allow forwarding cpm command line arguments to test mains

---

cpm/domain/project/project_composer.py
cpm/domain/project/project_descriptor.py
cpm/domain/project/project_descriptor_parser.py
cpm/domain/project_commands.py
scripts/cpm
setup.cfg
test/domain/test_project_composer.py
test/domain/test_project_descriptor_parser.py
test/e2e/test_cpm.py

This PR adds an option to the targets section that allows building and running the tests inside a Docker container built using a Dockerfile:
```yaml
targets:
default:
test_dockerfile: 'test.Dockerfile'
```

Allow using a Dockerfile for building and running tests
