cpm/__init__.py, cpm/domain/compilation_recipes/build.py, cpm/domain/compilation_recipes/test_recipe.py, test/compilation_recipes/test_build_recipe.py
=> remove Mac OS build and test recipes

cpm/__init__.py, cpm/api/install.py, cpm/api/publish.py, cpm/api/test.py, cpm/domain/install_service.py, cpm/domain/plugin_download.py, cpm/domain/plugin_installer.py, cpm/domain/project_loader.py, cpm/infrastructure/cpm_hub_connector_v1.py, cpm/infrastructure/filesystem.py, cpm/infrastructure/http_client.py, test/api/test_api_install.py, test/domain/test_install_service.py, test/domain/test_plugin_installer.py, test/domain/test_project_loader.py, test/infrastructure/test_cpm_hub_connector_v1.py
This still needs to be integration tested with CPM Hub
=> 62 allow plugin installation

cpm/domain/cmake_recipe.py, test/domain/test_cmake_recipe.py
=> Fixed cmakelists generation for projects without sources

cpm/api/publish.py, setup.py, test/domain/test_test_service.py
=> Support passing as argument the repository url on publish command

cpm/domain/plugin_loader.py, cpm/domain/project_loader.py, test/domain/test_plugin_loader.py, test/domain/test_project_loader.py
=> Fix plugins published with wrong version

cpm/domain/cmake_recipe.py, test/domain/test_cmake_recipe.py
=> Don't copy project binary to project root

.github/workflows/pythonapp.yml, pyproject.toml, setup.cfg, setup.py
Closes #105 
In this PR project setup has been adapted to standard PEP517 holding `setuptools` as system build backend:
* `pyproject.toml` has been defined with `setuptools` backend.
* `requirements.txt` and `setup.py` project information has been moved to `setup.cfg`.
* GitHub CI now installs `cpm-cli` as pip package in order to test all dependencies are resolved.
* An extra installation has been declared for run tests that it will install testing dependencies: 
`pip cpm-cli[testing]`
PyTest warnings has been removed. Now it will only run test classes with `unittest.TestCase` inheritance.
<details>
<summary>pytest output</summary>
```
================================================================================= test session starts …
```
=> Adapt project setup to PEP517 with setuptools backend

cpm/api/build.py, cpm/api/clean.py, cpm/api/update.py, cpm/domain/compilation_service.py, requirements.txt, setup.cfg, test/api/test_api_build.py, test/api/test_api_clean.py, test/api/test_api_update.py, test/domain/test_compilation_service.py
With this PR, the user can now run the following command:
```
$ cpm build <cpmbits_image>
```
CPM will pull from the cpmbits docker hub repositories and compile using the available images there.
=> Allow compiling for available docker targets

cpm/domain/install_service.py, test/domain/test_install_service.py
=> Print upgrade/downgrade when changing bit version

cpm/api/build.py, cpm/domain/compilation_service.py, cpm/domain/project/project.py, cpm/domain/project/project_composer.py, cpm/domain/project/project_descriptor.py, cpm/domain/project/project_descriptor_parser.py, cpm/domain/project_commands.py, test/api/test_api_build.py, test/domain/test_compilation_service.py, test/domain/test_project_descriptor_parser.py, test/e2e/environment/Dockerfile, test/e2e/test_cpm.py
With this PR, the user will be able to define an image or a Dockerfile for the compilation of a particular target.
Closes #163
=> Allow using docker for target compilation

cpm/domain/creation_service.py, cpm/domain/project/project_descriptor.py, cpm/domain/project/project_descriptor_parser.py, test/domain/test_project_descriptor_parser.py, test/e2e/test_cpm.py
=> Allow defining file containing main function per target

cpm/domain/project_commands.py, test/e2e/test_cpm.py
=> Fixed ninja command when building inside a container

cpm/domain/cmake/cmakelists_builder.py, cpm/domain/project/project.py, cpm/domain/project/project_composer.py, setup.cfg, test/domain/test_project_composer.py, test/e2e/test_cpm.py
=> Merge target defined compilation plan with build and test targets

cpm/api/build.py, cpm/domain/cmake/cmakelists_builder.py, cpm/domain/compilation_service.py, cpm/domain/project/project_composer.py, cpm/domain/project/project_loader.py, cpm/domain/project_commands.py, cpm/domain/test_service.py, test/api/test_api_build.py, test/domain/test_compilation_service.py, test/domain/test_project_composer.py, test/domain/test_project_loader.py, test/domain/test_test_service.py
=> Use target passed from the command line for building

cpm/domain/project/project_composer.py, test/domain/test_project_composer.py
=> Fix using different main file for target

cpm/domain/project/project_composer.py, cpm/domain/project/project_descriptor.py, cpm/domain/project/project_descriptor_parser.py, cpm/domain/project/project_loader.py, test/domain/test_project_composer.py, test/domain/test_project_descriptor_parser.py, test/e2e/environment/user_include.h, test/e2e/test_cpm.py
This MR adds support for user-defined include directories per compilation plan.
Closes #204.
=> Allow user defined includes per compilation plan

cpm/domain/cmake/cmakelists_builder.py, test/domain/test_cmakelists_builder.py
=> Compile and link test bit packages with test targets

cpm/domain/creation_service.py, test/domain/test_creation_service.py, test/e2e/test_cpm.py
=> Improve project skeleton creating tests directory

cpm/domain/cmake/cmakelists_builder.py, test/domain/test_cmakelists_builder.py
=> Avoid creating Done file in build directory

cpm/domain/project/project_composer.py, test/e2e/test_cpm.py
Second attempt. First fix was incomplete.
Closes #212
=> Fix compilation for target non described by bit, attempt 2

cpm/domain/bit_packager.py, cpm/domain/project/project_descriptor.py, test/domain/test_bit_packager.py, test/domain/test_project_descriptor_parser.py
=> Fix bit packager to publish described build packages in project descriptor

cpm/domain/cmake/cmakelists_builder.py, cpm/domain/project/project.py, cpm/domain/project/project_composer.py, cpm/infrastructure/cpm_hub_connector_v1.py
=> Fix include directories in test bit packages libraries

cpm/domain/project_commands.py
=> Remove ninja clean command from project clean

cpm/api/build.py, cpm/api/clean.py, cpm/api/install.py, cpm/api/prep.py, cpm/api/publish.py, cpm/api/test.py, cpm/domain/creation_service.py, cpm/domain/project/project_descriptor_parser.py, cpm/domain/project/project_loader.py, test/api/test_api_build.py, test/api/test_api_clean.py, test/api/test_api_install.py, test/api/test_api_prep.py, test/api/test_api_publish.py, test/api/test_api_test.py, test/domain/test_compilation_service.py, test/domain/test_creation_service.py, test/domain/test_project_loader.py, test/domain/test_publish_service.py, test/domain/test_test_service.py, test/e2e/test_cpm.py
This solution is a bit naive. Maybe a more sophisticated solution is required in the future.
Closes #180
=> Load project even if declared bits fail to load

cpm/api/create.py, test/api/test_api_create.py
=> Handle TemplateNotFound exception in create api

cpm/domain/project_commands.py
=> Add PROJECT_NAME and PROJECT_VERSION as environment variables for the docker build

cpm/domain/cmake/cmakelists_builder.py, cpm/domain/project/project_composer.py, cpm/domain/project/project_descriptor.py, test/domain/test_cmakelists_builder.py
=> Fix cflags and cppflags usage

cpm/api/build.py, cpm/domain/cmake/cmakelists_builder.py, cpm/domain/install_service.py, cpm/domain/project/project_descriptor_parser.py, cpm/domain/project_commands.py, cpm/infrastructure/cpm_hub_connector_v1.py, test/domain/test_cmakelists_builder.py, test/domain/test_project_descriptor_parser.py
=> Fix parsing of c and cpp compilation flags

cpm/domain/bit_installer.py, cpm/domain/compilation_service.py, cpm/domain/constants.py, cpm/domain/install_service.py, cpm/domain/project/project_composer.py, cpm/domain/project/project_loader.py, setup.cfg, test/domain/test_bit_installer.py, test/domain/test_project_composer.py, test/domain/test_project_loader.py, test/e2e/test_cpm.py
=> Install each bit version in its own directory

cpm/__init__.py, cpm/api/build.py, cpm/api/clean.py, cpm/api/create.py, cpm/api/init.py, cpm/api/install.py, cpm/api/prep.py, cpm/api/publish.py, cpm/api/test.py, cpm/argument_parser.py, cpm/domain/cmake/cmakelists_builder.py
=> Add documentation through command line

cpm/domain/project_commands.py
Instead of creating/removing a container per test executed, create a single container, then run all the tests inside it.
Closes #265
=> Improve test execution times when running tests inside container

cpm/domain/project_commands.py, setup.cfg
=> Replace bash by sh in docker command execution

cpm/__init__.py
=> Handle keyboard interrupts on main function
